#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}

# source function library
. wsl-functions

export IPINTERACTIVE=0
export WSAUTOMATED=2

UPDATELISTFILE="updatelist"

usage() {
  cat <<EOF
USAGE: ${MYNAME} NFREQUEST_FILE [LIST_OUTFILE]

The argument NFREQUEST_FILE is a file that contains a list of component name
and component Windows DUP file pair. The component name must be descriptive.
The pair is separated by an equal character with no spaces between values.

An example contents of the file:

bios=R715_BIOS_8NCP3_WN32_2.9.0.EXE
lifecycle controller=LC_APP_WIN_R296663.EXE

EOF
  exit 1
}

[ ! -z "$1" ] && echo $1 | grep -e "^-" -e "^help$" >/dev/null && usage
[ $# -lt 1 ] && usage

export INPUTFILE=$1
[ ! -z "$2" ] && UPDATELISTFILE=$2
UPDATELISTFILE="${WSENDPOINT}-${UPDATELISTFILE}"
MYCATALOG="${WSENDPOINT}-mycatalog.ini"

echo "### This is an auto-generated file" >${UPDATELISTFILE}
echo "### This is an auto-generated file" >${MYCATALOG}

echo "wsl enum DCIM_SoftwareIdentity -filter \"select * from DCIM_SoftwareIdentity where Status='Installed'\""
wsl enum DCIM_SoftwareIdentity -filter "select * from DCIM_SoftwareIdentity where Status='Installed'"
if [ ! -s ${RETURNFILE} ]; then
  echo -e "\nERROR: empty response file\n"
  exit 1
else
  echo -e "\nCreating internal catalog..."
  while read -e item ; do
    echo ${item} | grep ':ComponentID>' >/dev/null && export cid=$(echo ${item} | cut -d'>' -f2 | cut -d'<' -f1) && continue
    echo ${item} | grep ':ElementName>' >/dev/null && eln=$(echo ${item} | cut -d'>' -f2 | cut -d'<' -f1) && continue
    echo ${item} | grep ':InstanceID>' >/dev/null && iid=$(echo ${item} | cut -d'>' -f2 | cut -d'<' -f1) && continue
    echo ${item} | grep ':VersionString>' >/dev/null && ver=$(echo ${item} | cut -d'>' -f2 | cut -d'<' -f1) && continue
    if [ ! -z ${ver} ]; then
      echo "${cid}=${ver}=${iid}=${eln}" >> ${MYCATALOG}
      unset cid eln iid ver
    fi
  done < ${RETURNFILE}

  echo -e "\nGenerating the update list..."
  while read -e item ; do
    echo ${item} | grep "^#" >/dev/null && continue
    name=$(echo ${item} | cut -d'=' -f1)
    file=$(echo ${item} | cut -d'=' -f2)
    line=$( grep -i -m 1 "${name}" ${MYCATALOG} )
    cid=$( echo ${line} | cut -d'=' -f1 )
    ver=$( echo ${line} | cut -d'=' -f2 )
    iid=$( echo ${line} | cut -d'=' -f3 )
    eln=$( echo ${line} | cut -d'=' -f4 )
    echo "  ${eln}, ${cid}, ${ver}  ==>  ${file}"
    echo "## ${eln}, ${cid}, ${ver}" >> ${UPDATELISTFILE}
    echo "${iid}=${file}" >> ${UPDATELISTFILE} 
  done < ${INPUTFILE}
 
  cat <<EOF

IMPORTANT: 
Review the information above. Check that the DUP files you provided is 
applicable to the target system. Once verified, proceed to the next step 
using the file "${UPDATELISTFILE}".

EOF
fi

exit 0
