#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}

# source function library
WSLNOINIT=1
. wsl-functions

export IPINTERACTIVE=0
export WSAUTOMATED=2

UPDATELISTFILE="updatelist"

usage() {
  cat <<EOF
USAGE: ${MYNAME} WORKDIR iDRAC_INFO SHARE_INFO NFREQUEST_FILE

For iDRAC_INFO, provide: 
  IPADDRESS USERNAME PASSCODE

For SHARE_INFO, provide one of the following:
  cifs SHAREIPADDRESS SHAREDIR SHARENAME USERNAME PASSCODE
  nfs SHAREIPADDRESS SHAREDIR SHARENAME x x
  ftp SHAREIPADDRESS SHAREDIR x x x
  http SHAREIPADDRESS SHAREDIR x x x
  ftp SHAREIPADDRESS x x x x

For providing the arguments, replace the text in all-caps with actual values.
Otherwise, enter the text as is. SHAREDIR is the directory where the Windows
DUP files are located. If files are located in the root share, specify a dot
character.

NFREQUEST_FILE is a file that contains a list of component name and component
Windows DUP file pair. The component name must be descriptive. The pair is
separated by an equal character with no spaces between values.

An example contents of the file:
  bios=R715_BIOS_8NCP3_WN32_2.9.0.EXE
  lifecycle controller=LC_APP_WIN_R296663.EXE

EOF
  exit 1
}

[ ! -z "$1" ] && echo $1 | grep -e "^-" -e "^help$" >/dev/null && usage
[ $# -lt 11 ] && usage

WORKDIR=$1; shift
cd ${WORKDIR} || fMessageThenExit "ERROR: can't find ${WORKDIR}!" 1

export WSENDPOINT=$1; shift
export WSUSER=$1; shift
export WSPASS=$1; shift
sharetype=$1; shift
shareip=$1; shift
sharedir=$1; shift
sharename=$1; shift
shareuser=$1; shift
sharepass=$1; shift
INPUTFILE=$1; shift

lc-update1procnfrequest ${INPUTFILE} || fMessageThenExit "ERROR: failed to process request file!" 1
lc-update2updatefromshare ${sharetype} ${shareip} ${sharedir} ${sharename} ${shareuser} ${sharepass} || fMessageThenExit "ERROR: update from nfs has errors!" 1
lc-update3monwhiledownloading || fMessageThenExit "ERROR: failed job status detected!" 1
lc-update4rebootjob || fMessageThenExit "ERROR: reboot job failed!" 1
lc-update5schedulenow || fMessageThenExit "ERROR: schedule job failed!" 1
lc-update6monuntilcomplete 

exit 0
