#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}

# source function library
. wsl-functions

export IPINTERACTIVE=0
export WSAUTOMATED=2

UPDATELISTFILE="updatelist"
JOBSLISTFILE="updatejobs"

usage() {
  cat <<EOF

USAGE: ${MYNAME} SHARE_INFO [LIST_INFILE [JOBS_OUTFILE]]

For SHARE_INFO, provide one of the following:
  cifs SHAREIPADDRESS SHAREDIR SHARENAME USERNAME PASSCODE
  nfs SHAREIPADDRESS SHAREDIR SHARENAME x x
  ftp SHAREIPADDRESS SHAREDIR x x x
  http SHAREIPADDRESS SHAREDIR x x x
  ftp SHAREIPADDRESS x x x x

For providing the arguments, replace the text in all-caps with actual values.
Otherwise, enter the text as is. SHAREDIR is the directory where the Windows
DUP files are located. If files are located in the root share, you can specify
an empty value with double qoutes such as "" or a dot character.

EOF
  exit 1
}

[ $# -lt 6 ] && usage
echo $1 | grep -e "^-" -e "^help$" >/dev/null && usage
sharetype=$1; shift
shareip=$1; shift
sharedir=$1; shift
sharename=$1; shift
shareuser=$1; shift
sharepass=$1; shift
[ ! -z "$1" ] && UPDATELISTFILE=$1 && shift
[ ! -z "$1" ] && JOBSLISTFILE=$1 && shift

UPDATELISTFILE="${WSENDPOINT}-${UPDATELISTFILE}"
JOBSLISTFILE="${WSENDPOINT}-${JOBSLISTFILE}"

[ ! -f ${UPDATELISTFILE} ] && "ERROR: can't find ${UPDATELISTFILE} file." && exit 1
cat /dev/null >${JOBSLISTFILE}

if [ "${sharedir}" = "." ]; then
  sharedir=""
else
  echo "${sharedir}" | grep -v '/$' >/dev/null 2>&1 && sharedir=$( echo "${sharedir}" | sed 's/$/\\\//' )
fi

while read -e item ; do
  echo ${item} | grep "^#" >/dev/null && continue
  item2=$(echo ${item} | sed 's/"//g')
  instanceid=$(echo ${item2} | cut -d'=' -f1)
  dupfile=$(echo ${item2} | cut -d'=' -f2)
  [ -z "${dupfile}" ] && continue
  echo "Processing ${instanceid}... "
  case "${sharetype}" in
    cifs) 
         lcconfig update firmware cifs ${instanceid} ${shareuser} ${sharepass} ${shareip} ${sharedir}${dupfile} ${sharename}
         ;;
    nfs) 
         lcconfig update firmware nfs ${instanceid} ${shareip} ${sharedir}${dupfile} ${sharename}
         ;;
    http|ftp|tftp) 
         lcconfig update firmware xtp ${instanceid} ${sharetype} ${shareip} ${sharedir}${dupfile}
         ;;
    * ) 
         echo "ERROR: Unknown share type ${sharetype}!" 
         exit 1
         ;;
  esac
  [ ! -s ${RETURNFILE} ] && echo -e "\nWARNING: empty response file\n" && continue
  cat ${RETURNFILE} | grep "Selector" | grep "InstanceID" | cut -d'>' -f2 | cut -d'<' -f1 >>${JOBSLISTFILE}
done < ${UPDATELISTFILE}

echo "jobs saved to ${JOBSLISTFILE}"
exit 0

