#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}

# source function library
. wsl-functions

export OUTLEVEL=1
export IPINTERACTIVE=0
export WSAUTOMATED=1

JOBSLISTFILE="updatejobs"

[ ! -z "$1" ] && echo $1 | grep -e "^-" -e "^help$" >/dev/null && echo -e "USAGE: ${MYNAME} [JOBS_INFILE]\n" && exit 1

[ ! -z "$1" ] && JOBSLISTFILE=$1
JOBSLISTFILE="${WSENDPOINT}-${JOBSLISTFILE}"

[ ! -f ${JOBSLISTFILE} ] && "ERROR: can't find ${JOBSLISTFILE} file." && exit 1

for item in `cat ${JOBSLISTFILE}`; do
  echo ${item} | grep "^#" && continue
  item2=$(echo ${item} | sed 's/"//g')
  jlist="${jlist} InstanceID='${item2}' or"
done
jjlist=$(echo ${jlist} | head -c -3)

retry=18
while true; do
  [ -e "stop" ] && break
  export tpause=60
  echo    "wsl enum DCIM_LifecycleJob -filter \"select JobStatus from DCIM_LifecycleJob where ${jjlist}\""
  bash -c "wsl enum DCIM_LifecycleJob -filter \"select JobStatus from DCIM_LifecycleJob where ${jjlist}\""
  if [ -s ${RETURNFILE} ]; then
    grep -i fault ${RETURNFILE} >/dev/null
    if [ $? -eq 0 ]; then 
      export tpause=180
    else
      grep "JobStatus" ${RETURNFILE} | cut -d'>' -f2 | cut -d'<' -f1 | grep -vi "complete" >/dev/null
      [ $? -ne 0 ] && echo -e "\nAll status are complete." && break
    fi
  else
    [ ${retry} -eq 0 ] && echo -e "\nERROR: iDRAC no response retry limit reached." && exit 1
    echo "no response, iDRAC may be resetting, retry count ${retry}."
    retry=$((retry - 1))
    export tpause=180
  fi
  echo "wsl invoke DCIM_LCService GetRSStatus"
  bash -c "wsl invoke DCIM_LCService GetRSStatus"
  read -t ${tpause} -p "Pause for ${tpause} seconds, ctrl-c to stop."
  echo
done

exit 0
